Add Contact Page
umts/pvta-multiplatform pull request #233
Opened 2016-09-26 02:59 UTC by akaplo

Closes #211.  Adds a Contact page at `/about/contact` that gives a bunch of phone numbers for passengers.  Nothing special here.  @sherson, @werebus, @petermarathas, and @bgregg, any thoughts on UI or numbers/links that should or should not be included?

<img width="1058" alt="screen shot 2016-09-25 at 10 56 35 pm" src="https://cloud.githubusercontent.com/assets/7144148/18821392/a84480ae-8373-11e6-9bc4-78210eca702a.png">

2016-09-26 16:04 UTC, werebus commented on www/pages/contact/contact.html
> +      <div class="item item-button-right">
I'd lose SpecTrans.  It isn't really anything to do with the PVTA.

2016-09-26 16:11 UTC, werebus requested changes
Social media stuff?  PVTA does have a Twitter and Facebook page (with limited content)  So does UMTS.  I dunno.

2016-09-26 17:21 UTC, akaplo commented
I like the social media stuff; will add.

2016-09-28 14:54 UTC, akaplo commented
@werebus 
<img width="1058" alt="screen shot 2016-09-25 at 10 56 35 pm" src="https://cloud.githubusercontent.com/assets/7144148/18918791/e57344a4-8569-11e6-9ef0-8b0d737bfed9.png">

2016-09-28 15:20 UTC, werebus commented
Icons are a little inconsistent.

2016-09-28 15:21 UTC, akaplo commented
Sizes?  Yeah, I'm not sure why that is; they're supposed to all be the same.

2016-09-28 15:24 UTC, werebus commented
Well, presumably it's not a fixed-width font.  Buttons with "text" on them are usually as wide as the text requires, right?  It's hard to tell, but it looks like they're all the same height.

2016-09-28 15:25 UTC, akaplo commented
Sure, but the button doesn't have text; it has an icon.
Its only shown content is

`<i class="icon ion-social-facebook"></i>`

2016-09-28 16:06 UTC, akaplo commented
Fixed with some `padding-left` for the Facebook icon's text.

2016-09-28 22:53 UTC, merged