Route abbrev
umts/pvta-multiplatform pull request #235
Opened 2016-09-26 20:57 UTC by petermarathas

Closes #225 

Routes can still be searched by their short name, but the route abbreviation is used for display. Note also that route-list-factory still sorts routes by number using short name.

2016-09-28 15:15 UTC, akaplo commented
@petermarathas This seems right, but there's one issue: it will fail to properly display any already saved Favorite Routes (because they don't have the RouteAbbreviation saved), or any cached Routes in the `Routes and Stops` page (for the same reason).

2016-09-28 16:05 UTC, akaplo commented
CC failtures are OK.

2016-09-28 16:33 UTC, akaplo requested changes
See my main comment.

2016-10-03 17:01 UTC, akaplo commented
@petermarathas and I talked about a solution to my problem a few days ago.

2016-10-03 20:56 UTC, petermarathas commented on www/pages/my-buses/my-buses-controller.js
> +    localforage.getItem('updatedRoutes', function(err, updated) {
@akaplo This gets the job done, checks whenever my-buses is reloaded

2016-10-04 00:55 UTC, akaplo approved these changes

2016-10-04 00:55 UTC, merged