Stop Departure Ordering
umts/pvta-multiplatform pull request #256
Opened 2016-11-09 20:37 UTC by akaplo

Closes #246.  Sorts departures by Route Direction by default (thus, for example, allowing both a section of Mullins Center via CS departures **and** a section of OHill via Sylvan departures).  It also adds the option to sort departures by time.

There's a ton of logic changes (and even some simplification!) here.  @petermarathas and @bgregg, please review code and UI.  @sherson and @werebus, please give your opinions as well.

**CURRENT VIEW**
![image](https://cloud.githubusercontent.com/assets/7144148/20153725/1a6eb726-a692-11e6-989d-578da07f27e7.png)

**NEW VIEW (sorting by route direction)**
![image](https://cloud.githubusercontent.com/assets/7144148/20153742/2d904e8c-a692-11e6-88e2-d3e129c5481b.png)

**NEW VIEW (sorting by time; they run off the page as there's about 20)**
![image](https://cloud.githubusercontent.com/assets/7144148/20153772/4a75c734-a692-11e6-90f3-0abc017d5811.png)

2016-11-09 21:29 UTC, sherson commented
UI looks good.

2016-11-09 21:55 UTC, petermarathas requested changes
Looks good, but what if we stored the users preference (time vs. direction)? So if the person prefers sorting by time, they wouldn't need to change it each time they opened a stop.

Something like localforage.set({directionPreference: 1}) in the sort method

2016-11-09 21:56 UTC, petermarathas commented on www/pages/stop/stop-controller.js
> +  $scope.chooseFilter = function () {
Is this method used? Can't find it anywhere in the html or controller

2016-11-15 03:38 UTC, akaplo commented
@petermarathas implemented your comment, see [these lines](https://github.com/umts/pvta-multiplatform/pull/256/files#diff-9dc3af022ce52fcaff8bc239047fab0cR198).  Let me know if there's anything else.

2016-11-15 03:38 UTC, akaplo commented
@bgregg this is a big update, I'd like your opinion on the code if possible.

2016-11-15 03:39 UTC, akaplo commented
CC failures are OK.

2016-11-15 15:18 UTC, bgregg commented
Looking now, please hold

2016-11-15 16:43 UTC, petermarathas commented on www/pages/stop/stop-controller.js
> +  function loadOrdering () {
👍

2016-11-15 16:43 UTC, petermarathas approved these changes

2016-11-16 17:49 UTC, bgregg approved these changes
👍

2016-11-16 17:54 UTC, merged