Favorites from Routes And Stops page
umts/pvta-multiplatform pull request #268
Opened 2016-11-18 18:00 UTC by bgregg

Finally. You can now favorite routes and stops from the routes and stops page directly. Closes #209.

2016-11-18 18:37 UTC, akaplo requested changes
A few small things, but overall this is fantastic.

2016-11-18 18:37 UTC, akaplo commented on www/directives/route/route-directive.html
> +<button ng-class="liked ? 'button button-icon icon ion-ios-heart' : 'button button-icon icon ion-ios-heart-outline'" ng-click="liked = !liked; toggle(route); $event.stopPropagation();"></button>
Perhaps a comment about `$event.stopPropogation` would be nice here.

2016-11-18 18:37 UTC, akaplo commented on www/directives/stop/stop-directive.html
> +<button ng-class="liked ? 'button button-icon icon ion-ios-heart' : 'button button-icon icon ion-ios-heart-outline'" ng-click="liked = !liked; toggle(stop); $event.stopPropagation();"></button>
Perhaps a comment about `$event.stopPropogation` would be nice here.

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
>     * Get all the routes and stops
This comment doesn't match the function below it.

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +   $scope.redirectRoute = function(routeId){
Comment this and [this](https://github.com/umts/pvta-multiplatform/pull/268/files?diff=unified#diff-365f07089626b424259d271203b2ff1eR13).

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +  function stripDetails (routeList) {
We have a function called `prepareStops`, why not rename this to `prepareRoutes?`

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
>      /* Similar to prepareRoutes, we only
Move this comment to `prepareStops`' new location

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +  $scope.toggleStopHeart = function (stop) {
Comment this

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +  $scope.toggleRouteHeart = function(route){
Comment this.

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +      if(bool) {
Let's change this to be a `===`

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +      if (bool) {
Let's change this to be a `===`

2016-11-18 18:37 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
> +    $scope.display($scope.currentDisplay);
We have a [function](https://github.com/umts/pvta-multiplatform/pull/268/files?diff=unified#diff-365f07089626b424259d271203b2ff1eR170) (`redraw`) that does this for us...call it.

2016-11-18 19:05 UTC, bgregg commented
The rest of the CodeClimate issues are just "similar code found in other places" and so I think this is good. I also fixed your suggestions @akaplo.

2016-11-18 19:07 UTC, bgregg commented
Before:

<img width="1242" alt="screen shot 2016-11-18 at 2 07 03 pm" src="https://cloud.githubusercontent.com/assets/14984384/20442845/5283f07e-ad98-11e6-9bc3-635545f386ac.png">

2016-11-18 19:07 UTC, bgregg commented
Now:

<img width="1238" alt="screen shot 2016-11-18 at 2 06 21 pm" src="https://cloud.githubusercontent.com/assets/14984384/20442866/63e706a8-ad98-11e6-8a48-e999ddc3095c.png">

2016-11-19 03:02 UTC, akaplo commented on www/pages/routes-and-stops/routes-and-stops-controller.js
>     * Get all the routes and stops
Looks better now.

2016-11-19 03:02 UTC, akaplo approved these changes

2016-11-19 03:03 UTC, akaplo commented
Looks good to me!  Merging.

2016-11-19 03:04 UTC, merged