checkRouteTransit checks if the route is transit
umts/pvta-multiplatform pull request #273
Opened 2016-11-30 16:36 UTC by petermarathas

If there's no bus to get you somewhere, google tells you to walk. This instead shows a message saying there's no bus.

2016-11-30 21:55 UTC, akaplo commented on www/pages/plan-trip/plan-trip-controller.js
> +  var checkRouteTransit = function(route) {
You can/should define as `function checkRouteTransit (route)` for consistency with the rest of the app.

2016-11-30 21:56 UTC, akaplo commented on www/pages/plan-trip/plan-trip-controller.js
> +  var checkRouteTransit = function(route) {
Could it be renamed?  If I didn't know what it did, I wouldn't know what "check route transit" means.

2016-11-30 21:57 UTC, akaplo requested changes
My 2 comments and CC failures ("similar code" failures are OK for now).  Simple and nice!

2016-12-05 16:34 UTC, petermarathas commented
@akaplo <code>checkRouteTransit</code> changed to <code>function confirmValidRoute</code>.

2016-12-05 17:02 UTC, akaplo commented
Schweet. I'll approve, but fix your two CC issues before you merge please!

2016-12-05 17:03 UTC, akaplo approved these changes

2016-12-05 17:19 UTC, merged