Swipe To Delete Favorite Routes and Stops
umts/pvta-multiplatform pull request #385
Opened 2017-06-01 22:34 UTC by AkivaGreen

I want to resolve #379 with this pull request.

2017-06-01 22:36 UTC, AkivaGreen commented
I'm looking for a way to refresh the interface after deleting to show that the route/stop has been deleted. Also, it does delete the route/stop, however, I don't know if it is doing it correctly.

2017-06-02 16:05 UTC, werebus commented
Looks promising. If I understand the Ionic docs correctly, this isn't exactly a swipe-to-delete, but a swipe-to-reveal-a-delete-button?

@akaplo had a tool to record animated-GIF screencasts that was useful in these UI demonstration situations.

Also, we should look into the build failure. It's not caused by your code, as far as I can tell.

2017-06-02 18:20 UTC, akaplo commented
Looks promising indeed! I don't have time today, but I will review in full this weekend.

2017-06-02 19:50 UTC, AkivaGreen commented
The only thing I have left is getting it to remove the 'deleted' item from the list without having to do a browser refresh. Or should I do a browser refresh?

2017-06-03 19:11 UTC, akaplo commented
@AkivaGreen, since MyBuses has  [instance-variable arrays](https://github.com/umts/pvta-multiplatform/blob/master/src/pages/my-buses/my-buses.component.ts#L22) for both favorite routes and favorite stops, removing the favorite in question from the proper array would solve that.

You can see examples of how we did this in 1.x [here](https://github.com/umts/pvta-multiplatform/blob/ionic1/base/www/pages/my-buses/my-buses-controller.js#L79)

2017-06-03 19:29 UTC, akaplo requested changes
I know you're still working on deleting the favorites, but I'd also love to see some unit tests for the new methods!

2017-06-03 19:29 UTC, akaplo commented on src/pages/my-buses/my-buses.component.ts
> +    private stopSvc: FavoriteStopService, private routeSvc: FavoriteRouteService) {
Your naming for the service instances could be a little confusing - for example, the app has a [RouteService](https://github.com/umts/pvta-multiplatform/blob/master/src/providers/route.service.ts) **and** [FavoriteRouteService](https://github.com/umts/pvta-multiplatform/blob/master/src/providers/favorite0route.service.ts).  

I'd alleviate this with names like `favRouteSvc` and `favStopSvc`.

2017-07-07 04:33 UTC, akaplo commented
@AkivaGreen what's the status here?  Let me know if you're ready for me to look it over again.

2017-07-15 18:10 UTC, mboneil10 commented
@akaplo, @AkivaGreen gave me this PR/issue. He's currently working on something over in round-three.

2017-07-18 21:19 UTC, mboneil10 commented
Okay, so from my understanding of this issue, all I have to do is use an instance variable array for favorite routes/stops and supply unit tests? @akaplo @AkivaGreen

2017-07-23 23:29 UTC, mboneil10 commented
I've made a [new PR for this issue](https://github.com/umts/pvta-multiplatform/pull/408), so I'll close this one. Good work @AkivaGreen!

2017-07-23 23:29 UTC, closed without merging