Delete routes and stops
umts/pvta-multiplatform pull request #408
Opened 2017-07-22 15:37 UTC by mboneil10

Closes #379

2017-07-22 15:40 UTC, mboneil10 commented
Doesn't remove favorite routes and stops from the view as it does with trips. So, I can swipe to delete both stops and routes, but the view doesn't update unless I refresh. I used the instance-variable array for both routes and stops. What gives (@akaplo)? I'll look into this later.

2017-07-22 15:41 UTC, mboneil10 commented
Oops I'll update the tests so there isn't a CI fail! AGGGHHH

2017-07-22 15:44 UTC, mboneil10 commented
And yes, needs tests still. I put this PR up just so other people could help me figure out why the instance-variable arrays don't update the view automatically.

2017-07-23 20:26 UTC, akaplo requested changes
2 quick changes.

2017-07-23 20:26 UTC, akaplo commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.routes, {name: route.name});
So, you're asking [Lodash](https://lodash.com/docs/4.17.4#remove) to `remove` entries in the `this.routes` array whose `name` property matches the `name` property of the route passed to this function.  

The problem here is that routes don't have a `name` property!  This line should be
`_.remove(this.routes, {RouteId: route.RouteId})`. 

The reason why the [favoriteRouteService function](https://github.com/umts/pvta-multiplatform/blob/master/src/providers/favorite-route.service.ts#L56) works is that it's properly removing based on `RouteId`.

2017-07-23 20:26 UTC, akaplo commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.stops, {stopId: stopId});
Similar issue here as above, but this one's more subtle - `stopId` is the param that's passed to this function, but a stop object doesn't have a `stopId` property - it's called ` StopId` (note the capital `S`).  Woof.

2017-07-23 22:23 UTC, mboneil10 commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.routes, {name: route.name});
Ohhh. I saw `routeToRemove: Route`, and thought that `Route` would just be the name of the route. I was wrong. Great!

2017-07-23 22:23 UTC, mboneil10 commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.stops, {stopId: stopId});
WAT

2017-07-23 22:23 UTC, mboneil10 commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.stops, {stopId: stopId});
WHY

2017-07-23 22:24 UTC, mboneil10 commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.stops, {stopId: stopId});
(I'll be looking into this, no need to actually answer the above question of why)

2017-07-23 22:30 UTC, mboneil10 commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.routes, {name: route.name});
Wow that makes so much more sense to me. Thank you.

2017-07-23 22:35 UTC, mboneil10 commented
Next, tests

2017-07-23 23:23 UTC, akaplo commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.routes, {name: route.name});
Hooray! You're welcome.

2017-07-23 23:24 UTC, akaplo commented on src/pages/favorites/favorites.component.ts
> +    _.remove(this.routes, {name: route.name});
FYI the structure of all the Avail objects (like Route, RouteDetails, Stop, StopDeparture, etc) is currently best found on [the Swagger doc](http://bustracker.pvta.com/InfoPoint/swagger/ui/index).

2017-07-23 23:31 UTC, akaplo commented
Yup! If you have testing questions, totes throw them my way.

2017-07-25 12:40 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +      component.routes = [ this.route ];
Ohhhhh! That's how you do it. I was trying to call `this.routes`.

2017-07-25 12:40 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +        Color: '00467E'
Are all of these necessary? If so, is there any way to make a factory in ionic/angular?

2017-07-25 12:47 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +      expect(mockFavRouteSvc.remove).toHaveBeenCalledWith(this.route)
Do you need semicolons?

2017-07-25 12:50 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +      // Set the class-wide variable again (component isn't available in beforeAll?)
I wonder why. Hm

2017-07-25 12:54 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +        Color: '00467E'
And where did you get them? Swagger?

2017-07-25 13:22 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +        Color: '00467E'
Oh, I found it in [favorite route service](https://github.com/umts/pvta-multiplatform/blob/master/src/providers/favorite-route.service.ts). Isn't this technically a favorite route then? Or do all routes have these properties?

2017-07-25 15:29 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +        Color: '00467E'
This is indeed a favorite route - in this case specifically, I threw a debugger into the FavoritesComponent and copied one of _my_ favorite routes when it was loaded onto the page.

I don't know anything about factories here, but I hope so!  For this test, we technically could use any object with the `RouteId` property set, as that's all the code we're testing is looking for.

2017-07-25 15:31 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +      component.routes = [ this.route ];
👍 scope is difficult to understand in the tests - in general:
- Assign `this.xyz` variables in `beforeEach` or `beforeAll` and access them in `it()` blocks.  These variables have nothing to do with the `this.zyx` variables in the component.
- Set and get `this.zyx` variables that normally reside in the component via `component.zyx` in the `it()` blocks.

2017-07-25 15:32 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +      expect(mockFavRouteSvc.remove).toHaveBeenCalledWith(this.route)
Yes indeed.

2017-07-25 15:34 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +      // Set the class-wide variable again (component isn't available in beforeAll?)
I'd assume it has to do funky scoping - like maybe the `beforeEach()` that sets it doesn't always run before this one.  Like maybe we should be nesting a `describe()` somewhere we aren't, or something of that sort.

2017-07-25 16:55 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +      expect(mockFavRouteSvc.remove).toHaveBeenCalledWith(this.route)
I will add them in then

2017-07-25 16:55 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +      // Set the class-wide variable again (component isn't available in beforeAll?)
Right. I was thinking it was a timing thing, too.

2017-07-25 17:21 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +        Color: '00467E'
I'll look into factories... after this. Seems like a different issue all together. I can add it.

2017-07-26 17:48 UTC, mboneil10 commented
I'll follow the basic structure of what @akaplo laid out for the tests. It will only be two or three tests, so no big deal.

2017-07-27 20:59 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +    // Make an arbitrary route object available to each test
arbitrary stop object

2017-07-27 21:01 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +    // Make an arbitrary route object available to each test
arbitrary trip 🥇

2017-07-27 21:03 UTC, akaplo approved these changes

2017-07-27 21:03 UTC, akaplo commented
Hooray! Great job with this.

2017-07-27 21:27 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +    // Make an arbitrary route object available to each test
OOp

2017-07-27 21:27 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +    // Make an arbitrary route object available to each test
That's what copy and paste does to you, man.

2017-07-27 21:27 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +    // Make an arbitrary route object available to each test
Never again.

2017-07-28 12:43 UTC, mboneil10 commented on src/pages/favorites/favorites.component.spec.ts
> +    // Make an arbitrary route object available to each test
I just deleted those comments and left routes commented out.

2017-07-28 13:36 UTC, merged