Ionic 3.6
umts/pvta-multiplatform pull request #413
Opened 2017-08-04 02:48 UTC by akaplo

Closes #406! 🙌  🎊 🎉 

There are, believe it or not, no functional changes as a result of this.  Please see Ionic's [changelog](https://github.com/ionic-team/ionic/blob/f605f0a74c8fc3887e3ada8e380c42d4be2e640d/CHANGELOG.md) for a list of the framework's notable changes.

@werebus and @dfaulken I'd love both of your dogged attention to detail here, especially for sanity-checking package.json.

2017-08-04 14:16 UTC, werebus requested changes
Mostly questions on my part, although the README should be updated.

Seems fine to me otherwise.

2017-08-04 14:16 UTC, werebus commented on src/app/app.module.ts
> +import { BrowserModule } from '@angular/platform-browser';
So, what does this module do? I read the description in the Angular docs, and I still don't get it.

2017-08-04 14:16 UTC, werebus commented on package.json
> +    "ionic": "3.6.0",
There was debate about this before (#378), it looks like Ionic doesn't `preferGlobal` anymore. README should be updated, and any chance we want to revisit the issue in general?

2017-08-04 14:16 UTC, werebus commented on package.json
>    "dependencies": {
We dropped some `^`s here, mostly in Ionic plugins. Should we try being a smidge less rigid, or does it not matter?

2017-08-04 14:16 UTC, werebus commented on src/pages/favorites/favorites.component.spec.ts
> +    it('calls the FavoriteRouteService\'s remove() function', () => {
I know this was probably a linter, but I prefer the way it was before.

2017-08-04 17:07 UTC, akaplo commented on src/pages/favorites/favorites.component.spec.ts
> +    it('calls the FavoriteRouteService\'s remove() function', () => {
Meh..yeah.

2017-08-05 00:12 UTC, akaplo commented on src/app/app.module.ts
> +import { BrowserModule } from '@angular/platform-browser';
15 minutes of Googling turned up nothing, so I'm left with "because the changelog says so."  I might open a question on their forums.

2017-08-05 00:17 UTC, akaplo commented on package.json
>    "dependencies": {
Many of the new dependency versions were copied from Ionic's changelog, and every new Ionic release seems to want us to upgrade blocks of dependencies at a time, so I'd actually argue that lines [22](https://github.com/umts/pvta-multiplatform/pull/413/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22) through [38](https://github.com/umts/pvta-multiplatform/pull/413/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R38) and [50](https://github.com/umts/pvta-multiplatform/pull/413/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R50) through [52](https://github.com/umts/pvta-multiplatform/pull/413/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R50) stay un-`^`'d.

2017-08-05 00:21 UTC, akaplo commented on package.json
> +    "ionic": "3.6.0",
Yeah, we should probably revisit it.  fwiw, their docs still say to install globally.

![image](https://user-images.githubusercontent.com/7144148/28991155-6b07c216-7952-11e7-8664-333f479587b1.png)

2017-08-06 19:03 UTC, akaplo commented on package.json
> +    "ionic": "3.6.0",
I dropped a comment [here](https://github.com/ionic-team/ionic-cli/issues/2615) and we'll see what they come back with, but I think I **finally** understand what the difference between global vs local is in this case (see the comment).

2017-08-06 19:11 UTC, akaplo commented on package.json
>    "dependencies": {
I added ^s to a few.

2017-08-06 19:41 UTC, janpio commented on src/app/app.module.ts
> +import { BrowserModule } from '@angular/platform-browser';
BrowserModule (re)exports stuff like `ngIf` for use in browser apps, but also DOM stuff or Web worker. Before this stuff was provided by another import, now it was packaged together here.

2017-08-09 18:12 UTC, akaplo commented
@werebus any further thoughts here?

2017-08-09 19:02 UTC, janpio approved these changes

2017-08-15 21:33 UTC, mboneil10 commented on src/providers/toast.service.ts
> -
Whoops, sorry about that.

2017-08-15 21:35 UTC, mboneil10 approved these changes
This is fantastic!

2017-08-15 21:37 UTC, mboneil10 commented on src/pages/plan-trip/plan-trip.component.ts
> +      this.mapSvc.downloadGoogleMaps(() => this.mapsLoadedCallback(loadedTrip));
Callbacks.

2017-08-16 01:37 UTC, akaplo commented
I'm sending this one through; tack any further comments onto this PR and tag me.

2017-08-16 01:37 UTC, merged

2017-08-17 15:04 UTC, mboneil10 commented on src/pages/plan-trip/plan-trip.component.ts
> +      this.mapSvc.downloadGoogleMaps(() => this.mapsLoadedCallback(loadedTrip));
@akaplo just a callback, right?

2017-08-17 15:29 UTC, akaplo commented on src/pages/plan-trip/plan-trip.component.ts
> +      this.mapSvc.downloadGoogleMaps(() => this.mapsLoadedCallback(loadedTrip));
Yup! It's an [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) that calls another function.