Rework Stop Dropdown (Again)
umts/pvta-multiplatform pull request #422
Opened 2017-08-07 01:18 UTC by akaplo

Closes #407 in a continuation of #384.

**Left:** Android styling for sort-by-time **Right**: iOS styling for sort-by-`RouteDirection` with 1 Route expanded
![image](https://user-images.githubusercontent.com/7144148/29008948-689a14de-7aec-11e7-87da-cb2701e3cffb.png)

**The desktop version**
![image](https://user-images.githubusercontent.com/7144148/29008960-a5495a0c-7aec-11e7-9b4b-b77a8d641d1f.png)

2017-08-15 21:58 UTC, mboneil10 commented
I merged with master. Was there a code-related reason you hadn't done so? I figured it would be okay, but the commit can be reverted if needed.

2017-08-22 20:23 UTC, mboneil10 commented
@werebus has mentioned [Material Designs specs](https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-menu-controls) before, and I think in this case I see something that could be changed. The stop dropdown arrows could be pointing down when they are collapsed and up when they are expanded. This way, we'd indicate that this item is expandable, instead of a menu item.

2017-08-26 01:13 UTC, mboneil10 requested changes
I mentioned that the dropdown doesn't look like a dropdown due to the orientation of the arrows. All of the other changes are great.

2017-08-26 01:13 UTC, mboneil10 commented on src/pages/stop/stop.html
> +  <ion-list aria-label="upcoming departures at this stop" role="list">
I agree with this change. Great!

2017-08-26 01:13 UTC, mboneil10 commented on src/pages/stop/stop.html
> +                  {{departure.Times.sExact}}<br>
No other way to do this than a `br tag`?

2017-08-26 01:13 UTC, mboneil10 commented on src/pages/stop/stop.html
> +        <div [style.background-color]="'#'+routeList[direction.RouteId]?.Color" ion-item [hidden]="!isRouteDropdownShown(direction)" (click)="goToRoutePage(direction.RouteId)">
Have you seen how this looks with all of the route colors?

2017-08-26 01:13 UTC, mboneil10 commented on src/pages/stop/stop.html
> -          <!-- [ngClass]="{active: isRouteDropdownShown({{direction}})}" -->
It's nice that you did this in a completely separate commit. Thanks!

2017-08-26 01:23 UTC, mboneil10 commented
Another thing: OOC, when did we start displaying destinations? What is the purpose? For Bus Garage destinations, or...?

2017-08-28 13:57 UTC, akaplo commented
Good question - when ordering departures by `Direction`, there can be multiple departures with the same direction but different destinations, so it's nice to specify the destination in each entry.  I can't find a good example in the live feed right now, but I'll post a shot if I do.

2017-08-28 14:07 UTC, dfaulken commented
Bus Garage is the major case for us, but on the whole the other two properties have more variants per route than we do. So yes, buses can be leaving from the same stop, on the same route, and in the same direction — but still be going different places once they depart.

2017-08-28 15:21 UTC, mboneil10 commented
Alright, sounds good. Thank you. @dfaulken @akaplo

2017-08-28 15:51 UTC, mboneil10 commented
Do you have an updated screenshot you can share @akaplo?

2017-08-28 16:27 UTC, akaplo commented
@mboneil10 good point about the arrow directions.  I can't (legally?) make that change until I get home tonight, but you're welcome to if you're bored today and want to.

2017-08-30 02:47 UTC, akaplo commented
Arrows and screenshots updated. @mboneil10 or anyone else - any final thoughts?

2017-08-30 13:48 UTC, mboneil10 approved these changes

2017-08-30 13:48 UTC, mboneil10 commented
Looks good

2017-08-30 13:51 UTC, mboneil10 requested changes
Sorry, the arrow should face up when expanded and down when collapsed

2017-08-30 13:51 UTC, mboneil10 commented
I can make this fix for you @akaplo

2017-08-30 13:59 UTC, mboneil10 commented
<img width="1280" alt="screen shot 2017-08-30 at 9 59 27 am" src="https://user-images.githubusercontent.com/19267771/29876152-f701d510-8d69-11e7-9cf8-ebaf68e43a4d.png">

2017-08-30 14:01 UTC, mboneil10 commented
<img width="1119" alt="screen shot 2017-08-30 at 10 01 09 am" src="https://user-images.githubusercontent.com/19267771/29876227-2f2b6f14-8d6a-11e7-8928-3aba32a2e441.png">

2017-08-30 14:18 UTC, akaplo-cb commented
Woops, my bad! Thanks @mboneil10. 👍

2017-08-30 14:19 UTC, akaplo commented
Woops! My bad. Thanks @mboneil10 👍

2017-08-30 14:51 UTC, mboneil10 approved these changes

2017-08-30 16:50 UTC, merged